urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.contrib.auth.views import login, logout

from nyctbike.bike import views


#For example:
#
#urlpatterns = patterns('blog.views',
#    (r'^blog/(?P<year>\d{4})/$', 'year_archive', {'foo': 'bar'}),
#)
#
#In this example, for a request to /blog/2005/, Django will call the blog.views.year_archive() view, passing it these keyword arguments:

urlpatterns = patterns('',
                       (r'^$', views.welcome),
                       (r'^comments/', include('django.contrib.comments.urls')),
                       
                       (r'^stations/$', views.stations),
                       (r'^get_station_info/$', views.get_station_info),
                       (r'^serve_stations_data_supported/$', views.serve_stations_data, {'public':True, 'latest':False, 'onlysupported':True}),
                       (r'^serve_stations_data/$', views.serve_stations_data, {'public':True, 'latest':False, 'onlysupported':False}),
                       (r'^serve_stations_data_latest/$', views.serve_stations_data, {'public':True, 'latest':True, 'onlysupported':False}),
                       (r'^serve_stations_data_user/$', views.serve_stations_data, {'public':False, 'latest':False, 'onlysupported':False}),
                       
                       (r'^vote_station_ajax/$', views.vote_ajax, {'voteModelNameForeignKey':'votestation',
                                                                   'voteModelName':'VoteStation',
                                                                   'voteWhichModelName':'Station',
                                                                   'mynext':'/stations/'} ),
                       (r'^vote_idea_ajax/$', views.vote_ajax, {'voteModelNameForeignKey':'voteidea',
                                                                'voteModelName':'VoteIdea',
                                                                'voteWhichModelName':'Idea',
                                                                'mynext':'/ideas/'} ),
                       (r'^vote_designstation_ajax/$', views.vote_ajax, {'voteModelNameForeignKey':'votedesignstation',
                                                                'voteModelName':'VoteDesignStation',
                                                                'voteWhichModelName':'DesignStation',
                                                                'mynext':'/designstations/'} ),
                       (r'^vote_designbike_ajax/$', views.vote_ajax, {'voteModelNameForeignKey':'votedesignbike',
                                                                'voteModelName':'VoteDesignBike',
                                                                'voteWhichModelName':'DesignBike',
                                                                'mynext':'/designbikes/'} ),


                       
                       (r'^about/', TemplateView.as_view(template_name="about.html")),
                       (r'^thanks/', TemplateView.as_view(template_name="thanks.html")),
                       (r'^license/', TemplateView.as_view(template_name="licence.html")),
                       (r'^donate/', TemplateView.as_view(template_name="donate.html")),
                       
                       #    (r'^get_involved/$', views.get_involved),
#    (r'^get_support_detail/$', views.get_support_detail),


                       (r'^supportstation/$', views.support, {'what':'station'}),
                       (r'^supportidea/$', views.support, {'what':'idea'}),
                       (r'^supportdesignbike/$', views.support, {'what':'designbike'}),
                       (r'^supportdesignstation/$', views.support, {'what':'designstation'}),                       

                       (r'^idea/$', views.display, {'what':'idea'}),
                       (r'^designbike/$', views.display, {'what':'designbike'}),
                       (r'^designstation/$', views.display, {'what':'designstation'}),

                       (r'^ideas/$', views.ideas),
                       (r'^designstations/$', views.designList, {'dtype':'designstation'}),
                       (r'^designbikes/$', views.designList, {'dtype':'designbike'}),
                       (r'^supported/$', views.supported),

                       (r'^submitidea/$', views.submit, {'redirect':'/ideas', 'stype':'idea'}),
                       (r'^submitdesignstation/$', views.submit, {'redirect':'/designstations', 'stype':'designstation'}),
                       (r'^submitdesignbike/$', views.submit, {'redirect':'/designbikes', 'stype':'designbike'}),
                       
                       
                       (r'^submitstation/$', views.submitstation),
                       (r'^submitcommentstation/$', views.submitComment,  {'what':'station'}),
                       (r'^submitcommentidea/$', views.submitComment,  {'what':'idea'}),
                       (r'^submitcommentdesignstation/$', views.submitComment,  {'what':'designstation'}),
                       (r'^submitcommentdesignbike/$', views.submitComment,  {'what':'designbike'}),

                       
                       (r'^registration/register/$', views.register),
                       (r'^accounts/login/$', login),
                       (r'^accounts/logout/$', logout, {'next_page': '/accounts/login/'}),
                       
                       (r'^profile/$', views.profile),
                       (r'^form_profile_ajax/$', views.form_profile_ajax),
                       
                       (r'^user/$', views.userInfo),
                       # Uncomment the admin/doc line below to enable admin documentation:
                           # (r'^admin/doc/', views.include('django.contrib.admindocs.urls')),
                       
                       # Uncomment the next line to enable the admin:
                           (r'^admin/', include(admin.site.urls)),
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^site_media/(?P<path>.*)$',
                             'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT}),
                            )
    

bike/models.py
from django.db import models
import datetime

from django.contrib.auth.models import User

#to create tables:
##python manage.py validate
##python manage.py sqlall bike
##python manage.py syncdb ##<-create the tables

ACTIVATION_CHOICES = (
    ('A', 'Activated'),
    ('D', 'Desactivated')
    )

VOTE_CHOICES = (
    ('L', 'Like'),
    ('C', "Don't care"),
    ('D', "Don't like")
)

class VoteIt(models.Model):
    like = models.IntegerField() ##how many users like this idea
    dontlike = models.IntegerField()
    dontcare = models.IntegerField()
    
    activated = models.CharField(max_length=1, choices=ACTIVATION_CHOICES)

    nbsupports = models.IntegerField() ##number of support for the idea

    class Meta:
        abstract = True

class WhoDidThis(models.Model):
    creator = models.ForeignKey(User, related_name="%(app_label)s_%(class)s_related")
    when = models.DateTimeField(auto_now_add=True) ##date of creation of the idea    

    def __unicode__(self):
        return "%s %s" % (self.creator, self.when)

    class Meta:
        abstract = True
        ordering = ['-when']


class Station(WhoDidThis, VoteIt):

    STATION_CHOICES = (
        ('H', 'Home'),
        ('W', 'Work'),
        ('O', 'Other')
        )

    ##spatial coordinates (cheesy way...)
    lat = models.FloatField()
    lon = models.FloatField()

    why = models.CharField(max_length=1, choices=STATION_CHOICES)
    comment = models.TextField() #justification of the user (my work, my home...)

    def __unicode__(self):
        return "%g %g" % (self.lat, self.lon)

class Idea(WhoDidThis, VoteIt):
    CATEGORY_CHOICES = (
        ('W', 'Website'),
        ('F', 'Inovative financing'),
        ('B', 'Bikes maintenance'),
        ('O', 'Other')
        )
    
    name = models.CharField(max_length=400)
    description = models.TextField()
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES)
    
    def __unicode__(self):
        return "%s %s" % (self.name, self.description)



class Design(WhoDidThis, VoteIt):
    name = models.CharField(max_length=400)
    description = models.TextField()
    
    pict = models.ImageField(upload_to='pict/upload/')

    class Meta:
        abstract = True
        ordering = ['-when']

    def __unicode__(self):
        return "%s %s" % (self.name, self.description)


class DesignStation(Design):
    pass

class DesignBike(Design):
    pass




class VoteIdea(WhoDidThis):
    vote = models.CharField(max_length=1, choices=VOTE_CHOICES)
    which = models.ForeignKey(Idea)

    def __unicode__(self):
        return "%s" % (self.vote, self.which)
    
class VoteStation(WhoDidThis):
    vote = models.CharField(max_length=1, choices=VOTE_CHOICES)
    which = models.ForeignKey(Station)

    def __unicode__(self):
        return "%s" % (self.vote, self.which)

class VoteDesignStation(WhoDidThis):
    vote = models.CharField(max_length=1, choices=VOTE_CHOICES)
    which = models.ForeignKey(DesignStation)

    def __unicode__(self):
        return "%s" % (self.vote, self.which)

class VoteDesignBike(WhoDidThis):
    vote = models.CharField(max_length=1, choices=VOTE_CHOICES)
    which = models.ForeignKey(DesignBike)

    def __unicode__(self):
        return "%s" % (self.vote, self.which)



class Support(WhoDidThis):
    description = models.TextField()
    amount = models.FloatField()

    class Meta:
        abstract = True
        ordering = ['-when']

    def __unicode__(self):
        return "%s %s" % (self.description, self.supporter)


class SupportStation(Support):
    supported = models.ForeignKey(Station, related_name="%(app_label)s_%(class)s_related")

class SupportIdea(Support):
    supported = models.ForeignKey(Idea, related_name="%(app_label)s_%(class)s_related")

class SupportDesignBike(Support):
    supported = models.ForeignKey(DesignBike, related_name="%(app_label)s_%(class)s_related")

class SupportDesignStation(Support):
    supported = models.ForeignKey(DesignStation, related_name="%(app_label)s_%(class)s_related")


class News(WhoDidThis):
    title = models.CharField(max_length=400)
    content = models.TextField()


class UserProfile(models.Model):
#adapted from http://www.djangosnippets.org/snippets/494/
#using UN country and 3 char code list from http://unstats.un.org/unsd/methods/m49/m49alpha.htm
#correct as of 17th October 2008

    COUNTRY_CHOICES = (
        ('AFG', 'Afghanistan'), 
        ('ALA', 'Aland Islands'),
        ('ALB', 'Albania'),
        ('DZA', 'Algeria'),
        ('ASM', 'American Samoa'),
        ('AND', 'Andorra'),
        ('AGO', 'Angola'),
        ('AIA', 'Anguilla'),
        ('ATG', 'Antigua and Barbuda'),
        ('ARG', 'Argentina'),
        ('ARM', 'Armenia'),
        ('ABW', 'Aruba'),
        ('AUS', 'Australia'),
        ('AUT', 'Austria'),
        ('AZE', 'Azerbaijan'),
        ('BHS', 'Bahamas'),
        ('BHR', 'Bahrain'),
        ('BGD', 'Bangladesh'),
        ('BRB', 'Barbados'),
        ('BLR', 'Belarus'),
        ('BEL', 'Belgium'),
        ('BLZ', 'Belize'),
        ('BEN', 'Benin'),
        ('BMU', 'Bermuda'),
        ('BTN', 'Bhutan'),
        ('BOL', 'Bolivia'),
        ('BIH', 'Bosnia and Herzegovina'),
        ('BWA', 'Botswana'),
        ('BRA', 'Brazil'),
        ('VGB', 'British Virgin Islands'),
        ('BRN', 'Brunei Darussalam'),
        ('BGR', 'Bulgaria'),
        ('BFA', 'Burkina Faso'),
        ('BDI', 'Burundi'),
        ('KHM', 'Cambodia'),
        ('CMR', 'Cameroon'),
        ('CAN', 'Canada'),
        ('CPV', 'Cape Verde'),
        ('CYM', 'Cayman Islands'),
        ('CAF', 'Central African Republic'),
        ('TCD', 'Chad'),
        ('CIL', 'Channel Islands'),
        ('CHL', 'Chile'),
        ('CHN', 'China'),
        ('HKG', 'China - Hong Kong'),
        ('MAC', 'China - Macao'),
        ('COL', 'Colombia'),
        ('COM', 'Comoros'),
        ('COG', 'Congo'),
        ('COK', 'Cook Islands'),
        ('CRI', 'Costa Rica'),
        ('CIV', 'Cote d\'Ivoire'),
        ('HRV', 'Croatia'),
        ('CUB', 'Cuba'),
        ('CYP', 'Cyprus'),
        ('CZE', 'Czech Republic'),
        ('PRK', 'Democratic People\'s Republic of Korea'),
        ('COD', 'Democratic Republic of the Congo'),
        ('DNK', 'Denmark'),
        ('DJI', 'Djibouti'),
        ('DMA', 'Dominica'),
        ('DOM', 'Dominican Republic'),
        ('ECU', 'Ecuador'),
        ('EGY', 'Egypt'),
        ('SLV', 'El Salvador'),
        ('GNQ', 'Equatorial Guinea'),
        ('ERI', 'Eritrea'),
        ('EST', 'Estonia'),
        ('ETH', 'Ethiopia'),
        ('FRO', 'Faeroe Islands'),
        ('FLK', 'Falkland Islands (Malvinas)'),
        ('FJI', 'Fiji'),
        ('FIN', 'Finland'),
        ('FRA', 'France'),
        ('GUF', 'French Guiana'),
        ('PYF', 'French Polynesia'),
        ('GAB', 'Gabon'),
        ('GMB', 'Gambia'),
        ('GEO', 'Georgia'),
        ('DEU', 'Germany'),
        ('GHA', 'Ghana'),
        ('GIB', 'Gibraltar'),
        ('GRC', 'Greece'),
        ('GRL', 'Greenland'),
        ('GRD', 'Grenada'),
        ('GLP', 'Guadeloupe'),
        ('GUM', 'Guam'),
        ('GTM', 'Guatemala'),
        ('GGY', 'Guernsey'),
        ('GIN', 'Guinea'),
        ('GNB', 'Guinea-Bissau'),
        ('GUY', 'Guyana'),
        ('HTI', 'Haiti'),
        ('VAT', 'Holy See (Vatican City)'),
        ('HND', 'Honduras'),
        ('HUN', 'Hungary'),
        ('ISL', 'Iceland'),
        ('IND', 'India'),
        ('IDN', 'Indonesia'),
        ('IRN', 'Iran'),
        ('IRQ', 'Iraq'),
        ('IRL', 'Ireland'),
        ('IMN', 'Isle of Man'),
        ('ISR', 'Israel'),
        ('ITA', 'Italy'),
        ('JAM', 'Jamaica'),
        ('JPN', 'Japan'),
        ('JEY', 'Jersey'),
        ('JOR', 'Jordan'),
        ('KAZ', 'Kazakhstan'),
        ('KEN', 'Kenya'),
        ('KIR', 'Kiribati'),
        ('KWT', 'Kuwait'),
        ('KGZ', 'Kyrgyzstan'),
        ('LAO', 'Lao People\'s Democratic Republic'),
        ('LVA', 'Latvia'),
        ('LBN', 'Lebanon'),
        ('LSO', 'Lesotho'),
        ('LBR', 'Liberia'),
        ('LBY', 'Libyan Arab Jamahiriya'),
        ('LIE', 'Liechtenstein'),
        ('LTU', 'Lithuania'),
        ('LUX', 'Luxembourg'),
        ('MKD', 'Macedonia'),
        ('MDG', 'Madagascar'),
        ('MWI', 'Malawi'),
        ('MYS', 'Malaysia'),
        ('MDV', 'Maldives'),
        ('MLI', 'Mali'),
        ('MLT', 'Malta'),
        ('MHL', 'Marshall Islands'),
        ('MTQ', 'Martinique'),
        ('MRT', 'Mauritania'),
        ('MUS', 'Mauritius'),
        ('MYT', 'Mayotte'),
        ('MEX', 'Mexico'),
        ('FSM', 'Micronesia, Federated States of'),
        ('MCO', 'Monaco'),
        ('MNG', 'Mongolia'),
        ('MNE', 'Montenegro'),
        ('MSR', 'Montserrat'),
        ('MAR', 'Morocco'),
        ('MOZ', 'Mozambique'),
        ('MMR', 'Myanmar'),
        ('NAM', 'Namibia'),
        ('NRU', 'Nauru'),
        ('NPL', 'Nepal'),
        ('NLD', 'Netherlands'),
        ('ANT', 'Netherlands Antilles'),
        ('NCL', 'New Caledonia'),
        ('NZL', 'New Zealand'),
        ('NIC', 'Nicaragua'),
        ('NER', 'Niger'),
        ('NGA', 'Nigeria'),
        ('NIU', 'Niue'),
        ('NFK', 'Norfolk Island'),
        ('MNP', 'Northern Mariana Islands'),
        ('NOR', 'Norway'),
        ('PSE', 'Occupied Palestinian Territory'),
        ('OMN', 'Oman'),
        ('PAK', 'Pakistan'),
        ('PLW', 'Palau'),
        ('PAN', 'Panama'),
        ('PNG', 'Papua New Guinea'),
        ('PRY', 'Paraguay'),
        ('PER', 'Peru'),
        ('PHL', 'Philippines'),
        ('PCN', 'Pitcairn'),
        ('POL', 'Poland'),
        ('PRT', 'Portugal'),
        ('PRI', 'Puerto Rico'),
        ('QAT', 'Qatar'),
        ('KOR', 'Republic of Korea'),
        ('MDA', 'Republic of Moldova'),
        ('REU', 'Reunion'),
        ('ROU', 'Romania'),
        ('RUS', 'Russian Federation'),
        ('RWA', 'Rwanda'),
        ('BLM', 'Saint-Barthelemy'),
        ('SHN', 'Saint Helena'),
        ('KNA', 'Saint Kitts and Nevis'),
        ('LCA', 'Saint Lucia'),

bike/templates/about.html
{% extends "base.html" %}

{% block js %}

{% endblock %}

{% block content %}

<p>
  We are good people.
</p>

{% endblock %}

bike/templates/designlist.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" media="screen" type="text/css" title="Design espace" href="{{ MEDIA_URL }}css/form.css" />
<link rel="stylesheet" media="screen" type="text/css" title="Design espace" href="{{ MEDIA_URL }}css/brainstorming.css" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/vote.js"></script>
{% endblock %}

{% block content %}

<h1>
  Submitted {% if type == 'designstation' %} station {% else %} bike {% endif %} designs.
</h1>

<p>
  <a href="/submit{{ type }}" class="add_{{ type }}">Submit a new {% if type == 'designstation' %} station {% else %} bike {% endif %} design</a>
</p>

{% for object in mydesigns  %}
{% include 'display.html' %}
{% endfor %}

{% endblock %}

bike/templates/display_comment.html
<a class="creator" href="/user?username={{ comment.creator }}" title="see all contributions by: {{ comment.creator }}">{{ comment.creator }}</a><span class="ondate">, on:{{ comment.when }} </span><br/>

<!--vote: send POST data because side effects-->
<div class="encompass_vote_suppot">
  <span class="vote">vote:</span>
  <form id="form_votecomment_like_{{ comment.id }}" action="" method="post"> <!--action is "/vote_comment/" if not ajax-->
    <input type="hidden" name="idcomment" value="{{ comment.id }}"/>
    <input type="hidden" name="type" value="like"/>
    <input type="button" value="+ :{{ comment.like }}" class="like" title="like"/> <!--type has to be button and not submit as the POST is done by ajax-->
  </form>

  <form id="form_votecomment_dontcare_{{ comment.id }}" action="" method="post"> <!--action is "/vote_comment/" if not ajax-->
    <input type="hidden" name="idcomment" value="{{ comment.id }}"/>
    <input type="hidden" name="type" value="dontcare"/>
    <input type="button" value="= :{{ comment.dontcare }}" class="dontcare" title="don't care"/>
  </form>


  <form id="form_votecomment_dontlike_{{ comment.id }}" action="" method="post"> <!--action is "/vote_comment/" if not ajax-->
    <input type="hidden" name="idcomment" value="{{ comment.id }}"/>
    <input type="hidden" name="type" value="dontlike"/>
    <input type="button" value="- :{{ comment.dontlike }}" class="dontlike" title="don't like"/>
  </form>    
  <span class="level2idea_{{ comment.id }}" style="color:red; font-size:9pt;"></span> <!--already voted-->
</div>
<br/>

<p>
  {{ comment.content|linebreaks }}
</p>

bike/templates/display_station.html
{% load comments %}

<!-- we are obliged to put it here because this part is loaded via ajax-->
<script type="text/javascript" src="{{ MEDIA_URL }}js/vote.js"></script>

{% if display_station %}

<div class="stations">

  {% if display_link %}
  <a href="/stations?id={{object.id}}">
    {% endif %}
    <span class="stationtitle">lat:
      <span id="s_lat">{{object.lat }}</span> lon:<span id="s_lon">{{ object.lon}}</span></span>
    {% if display_link %}
  </a>
  {% endif %}
  <br/>
  <div class="stationsdetails">
    created by 
    <a class="creator" href="/user?username={{ object.creator }}" title="see all contributions by: {{ object.creator }}">{{ object.creator }}</a> on {{ object.when }} <br/>
    {% if display_link %}
    <a href="/stations?id={{object.id}}">
      {% endif %}
      <span class="titlecomment">comments:</span>
      {% if display_link %}
    </a>
    {% endif %}
    {% get_comment_count for object as comment_count %}  {{ comment_count }}. <br/>

    <div class="vote_station_ajax">
      {% include 'vote.html' %}
      <span class="station_{{ object.id }}" style="color:red; font-size:9pt;"></span><!--already voted-->
    </div>

    <p>
      <br/>
    </p>
  </div>

  <p>Why: {{ object.get_why_display }}</p>
  <p>Details: {{ object.comment|linebreaks }}</p>
</div>

{% endif %}

{% if display_comments %}

<p>
  <a href="/submitcommentstation?id={{myid}}&next=/stations?id={{myid}}"
     class="add_comment">add a comment</a> <br/> {% if  object.nbcomments  > 0 %} Comments: {% endif %}
</p>

{% get_comment_list for object as comment_list  %}
{% for comment in comment_list reversed %}

<a class="creator" href="/user?username={{ comment.user.username }}" title="see all contributions by: {{ comment.user.username }}">{{ comment.user.username }}</a><span class="ondate">, on:{{ comment.submit_date }} </span><br/>

<p>
  {{ comment.comment|linebreaks }}
</p>


{% endfor %}

{% endif %}

bike/templates/gm.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" >
  <head>
    <title>NYCT Bike</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" media="screen" type="text/css" title="Design espace" href="../../site_media/css/style_centered.css" />
    {% block css %}
    
    {% endblock %}

<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>


<script type="text/javascript"
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>

<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?sensor=false">
</script>

<script type="text/javascript"
    src="../../site_media/js/station.js">
</script>




</head>

<body onload="initialize()">

  <div id="map_canvas" style="width:50%; height:50%"></div>

  <p>Lat:
  <span id="lat"></span><br/>
Long:
  <span id="long"></span>
  </p>

</body>


</html>

bike/templates/ideas.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" media="screen" type="text/css" title="Design espace" href="{{ MEDIA_URL }}css/form.css" />
<link rel="stylesheet" media="screen" type="text/css" title="Design espace" href="{{ MEDIA_URL }}css/brainstorming.css" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/vote.js"></script>
{% endblock %}

{% block content %}

<h1>
Submitted ideas per categories
<img src="{{ MEDIA_URL }}pict/jenbike_B.png" alt="pict" title="category: Bike station design"/>
<img src="{{ MEDIA_URL }}pict/jenbike_W.png" alt="pict" title="category: Bike and bikes maintenance"/>
<img src="{{ MEDIA_URL }}pict/jenbike_F.png" alt="pict" title="category: Inovative financing"/>
<img src="{{ MEDIA_URL }}pict/jenbike_O.png" alt="pict" title="category: Other (website/mobile apps improvement...)"/>
</h1>

<p>
  <a href="/submitidea?next=/ideas" class="add_idea">Submit a new idea</a>
</p>

<div class="line">

  <div id="cat_maintenance">
    <h2>Bikes Maintenance</h2>

    <div id="cat_maintenance_box">
      {% for type, values in idea_list_B.items  %}
      {% for object in values  %}
      {% include 'display.html' %}
      {% endfor %}
      {% endfor %}
    </div>

  </div>

  <div id="cat_finance">
    <h2>Inovative financing</h2>


    <div id="cat_finance_box">
      {% for type, values in idea_list_F.items  %}
      {% for object in values  %}
      {% include 'display.html' %}
      {% endfor %}
      {% endfor %}
    </div>

  </div>

</div>

<div class="line">

  <div id="cat_website">
    <h2>Participative tools (website, mobile apps...)</h2>

    <div id="cat_website_box">
      {% for type, values in idea_list_W.items  %}
      {% for object in values  %}
      {% include 'display.html' %}
      {% endfor %}
      {% endfor %}
    </div>

  </div>


  <div id="cat_other">
    <h2>Other...</h2>

    <div id="cat_other_box">
      {% for type, values in idea_list_O.items  %}
      {% for object in values  %}
      {% include 'display.html' %}
      {% endfor %}
      {% endfor %}
    </div>

  </div>

</div>

{% endblock %}

bike/templates/stations.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" media="screen" type="text/css" title="Design espace" href="{{ MEDIA_URL }}css/form.css" />  
{% endblock %}

{% block googlemap %}
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/mapit.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/all_stations.js"></script>
{% endblock %}


{% block content %}

<div id="map_canvas"></div>


<p>click on a marker on the map to display info/rate/comment a station</p>
<a class="add_station" href="/submitstation">Submit your own stations</a>

<p id="ajax">

<p>

{% endblock %}

bike/templates/submitcomment.html
{% extends "base.html" %}
{% load comments %}

{% block css %}
<link rel="stylesheet" media="screen" type="text/css" title="Design espace" href="{{ MEDIA_URL }}css/form.css" />   
{% endblock %}


{% block js %}

{% endblock %}


{% block content %}

{% if what == 'station' %}
<p> Comment for station: lat: {{ object.lat }}, lon: {{ object.lon }} </p>

{% else %}
<p> Comment for : {{ object.name }} </p>
{% endif %}


{% if form.errors %} 
<p class="errors">
  Please correct the error{{ form.errors|pluralize }} below.
</p>
{% endif %}


{% get_comment_form for object as form %}
<table>
  <form action="{% comment_form_target %}" method="post">{% csrf_token %}
    {{ form }}

    <input type="hidden" name="next" value="/{{ what }}s?id={{ myid }}" />

    <tr>
      <td>
	<!--<td colspan="2">-->
	<input type="submit" name="submit" value="Post">
	<!--<input type="submit" name="preview" value="Preview">-->
      </td>
    </tr>
  </form>
</table>

{% endblock %}

bike/templates/thanks.html
{% extends "base.html" %}

{% block js %}

{% endblock %}

{% block content %}

<p>
  Thank you for your support!
</p>

{% endblock %}